# Fuentes
font_family     JetBrainsMono Nerd Font
bold_font       auto
font_size       13.0
text_composition_strategy legacy
# Transpaencia y Blur (esto último lo maneja Hyprland)
background_opacity 0.90
dynamic_background_opacity yes

# Ventana
window_padding_width 15
confirm_os_window_close 0

# Colores 
background #000000
foreground #ffffff
selection_background #000000
selection_foreground #ffffff

# Cursor
cursor #4682b4
cursor_shape beam
cursor_beam_thickness 1.5

# Pestañas (Tabs)
tab_bar_style powerline
active_tab_foreground   #11111b
active_tab_background   #cba6f7
inactive_tab_foreground #cdd6f4
inactive_tab_background #181825


#jaja te quiero.
