# Fuentes
font_family     JetBrainsMono Nerd Font
bold_font       auto
font_size       13.0
text_composition_strategy legacy
background_opacity 0.90
dynamic_background_opacity yes

# ventana
window_padding_width 15
confirm_os_window_close 0

# colores 
background #000000
foreground #ffffff
selection_background #ffffff
selection_foreground #000000

# cursor
cursor #FFFFFF
cursor_shape beam
cursor_beam_thickness 1.5

# pestañas 
tab_bar_style powerline
active_tab_foreground   #11111b
active_tab_background   #cba6f7
inactive_tab_foreground #cdd6f4
inactive_tab_background #181825

#tweaks
map ctrl+left send_text all \x1bb
map ctrl+right send_text all \x1bf

map ctrl+backspace send_text all \x17
#jaja te quiero.
